"use client";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

import { Provider, useDispatch, useSelector } from "react-redux";
import Navbar from "./_Components/Navbar";
import store, { AppDispatch } from "@/redux/store";
import { RootState } from "@/Type/type";
import { useEffect } from "react";
import { fetchgetAllJobs } from "@/redux/action";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body style={{ margin: 0, padding: 0 }}>{children}</body>
      </html>
    </Provider>
  );
}
